### ISSUE TITLE
ADFS is not waiting for Authenticator request

### ISSUE THREAD

**Issue by codyprashant** [bacza/aws-saml-session#2]
Normally the ADFS having MFA enabled will redirect the ADFS login page to the authenticator prompt confirmation page. But this code is not waiting for that and return in response with MFA page.

**Comment by bacza** [comment]
It's been a while, but for anyone interested - I've created another package [aws-saml-session-mfa](https://www.npmjs.com/package/aws-saml-session-mfa), which supersedes this one and adds more features like handling MFA or supporting different kinds of identity providers. Please give it a try!
